apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic-qa
  namespace: qa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pet-clinic
      environment: qa
  template:
    metadata:
      labels:
        app: pet-clinic
        environment: qa
    spec:
      containers:
      - name: pet-clinic
        image: ramesh316/sample:latest
        ports:
        - containerPort: 8080
